version: '3.8'

services:
  mcp-google-maps:
    build: .
    container_name: mcp-google-maps-server
    ports:
      - "3200:3200"
    environment:
      - MCP_SERVER_PORT=3200
      - MAP_API_PROVIDER=google
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-openstreetmap:
    build: .
    container_name: mcp-osm-server
    ports:
      - "3201:3201"
    environment:
      - MCP_SERVER_PORT=3201
      - MAP_API_PROVIDER=osm
    command: ["--port", "3201", "--provider", "osm"]
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-riskscape:
    build: .
    container_name: mcp-riskscape-server
    ports:
      - "3202:3202"
    environment:
      - MCP_SERVER_PORT=3202
      - MAP_API_PROVIDER=riskscape
      - RISKSCAPE_API_KEY=${RISKSCAPE_API_KEY}
      - RISKSCAPE_API_URL=${RISKSCAPE_API_URL:-https://api.riskscape.pro}
    command: ["--port", "3202", "--provider", "riskscape"]
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge